name: Lint

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13.3"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pylint black autoflake
      - name: Run autoflake
        run: autoflake --in-place --remove-unused-variables --remove-all-unused-imports .
      - name: Run black
        run: black . --check --line-length 88
      - name: Run flake8
        run: flake8 . --max-line-length=88 --exclude=.venv,__pycache__
      - name: Run pylint
        run: pylint *.py --max-line-length=88
